In [1]:
import numpy as np
import time

In [8]:
#vector creation 
a=np.zeros(4)
print(f'np.zeros(4): a={a}, a.shape={a.shape}, a.datatype={a.dtype}')
b=np.zeros((4,5)) # number of rows, number of columns 
print(f'np.zeros(4): b={b}, b.shape={b.shape}, b.datatype={b.dtype}')
c=np.random.random_sample((4,5)) #number of rows and number of columns 
print(f'np.random.random_sample(4): c={c}, c.shape={c.shape}, c.datatype={c.dtype}')

np.zeros(4): a=[0. 0. 0. 0.], a.shape=(4,), a.datatype=float64
np.zeros(4): b=[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]], b.shape=(4, 5), b.datatype=float64
np.random.random_sample(4): c=[[0.30111587 0.23390697 0.94818515 0.84144086 0.03545337]
 [0.58992884 0.11150483 0.86703436 0.20315308 0.46937025]
 [0.96628445 0.85610993 0.85572134 0.32130988 0.40514131]
 [0.92949986 0.42419519 0.69046913 0.51455708 0.73070259]], c.shape=(4, 5), c.datatype=float64


In [12]:
# Numpy routine which allocates memory and fill arrays with value but do not accept shape as input arguments 
a=np.arange(0,100,20) #start, stop, step 
print(f"np.arange(4.):     a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a=np.random.rand(4,5); # generates random number between 0 and 1 --> basically same as random_sample 
print(f"np.random.rand(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.arange(4.):     a = [ 0 20 40 60 80], a shape = (5,), a data type = int32
np.random.rand(4): a = [[0.41178025 0.8972574  0.87083606 0.58677519 0.54530935]
 [0.12779778 0.19073412 0.3530899  0.99708339 0.7630204 ]
 [0.57620214 0.0263633  0.61383291 0.14357318 0.37045362]
 [0.02892378 0.69796445 0.35275213 0.6673237  0.59051117]], a shape = (4, 5), a data type = float64


In [14]:
# numpy routines allocate memory and fill with user specified values 
a=np.array([5,4,3,2]); print(f"np.array([5,4,3,2]):  a = {a},     a shape = {a.shape}, a data type = {a.dtype}")
a=np.array([5.,4,3,2]); print(f"np.array([5.,4,3,2]): a = {a}, a shape = {a.shape}, a data type = {a.dtype}") #numpy arrays are homogenous 
# --> all the same data types 

np.array([5,4,3,2]):  a = [5 4 3 2],     a shape = (4,), a data type = int32
np.array([5.,4,3,2]): a = [5. 4. 3. 2.], a shape = (4,), a data type = float64


In [19]:
# indexing 
# vector indexing operations on 1-D vectors 
a=np.arange(10)
print(a)

#access an element
print(f"a[2].shape: {a[2].shape} a[2]  = {a[2]}, Accessing an element returns a scalar")

# access the last element, negative indexes count from the end
print(f"a[-1] = {a[-1]}")


#indexs must be within the range of the vector or they will produce and error
try:
    c=a[10]
except Exception as e:
    print(e)

[0 1 2 3 4 5 6 7 8 9]
a[2].shape: () a[2]  = 2, Accessing an element returns a scalar
a[-1] = 9
index 10 is out of bounds for axis 0 with size 10


In [25]:
# vector slicing operations 
a=np.arange(10)
print(f"a         = {a}")

#access 5 consectuvie elements (start: stop: step)
c=a[2:7:2];   print("a[2:7:1] = ", c)

# access all elements index 3 and above
c = a[3:];        print("a[3:]    = ", c)

# access all elements below index 3
c = a[:3];        print("a[:3]    = ", c)

# access all elements
c = a[:];         print("a[:]     = ", c)

a         = [0 1 2 3 4 5 6 7 8 9]
a[2:7:1] =  [2 4 6]
a[3:]    =  [3 4 5 6 7 8 9]
a[:3]    =  [0 1 2]
a[:]     =  [0 1 2 3 4 5 6 7 8 9]


In [29]:
# single vector operation 
a = np.array([1,2,3,4])
print(f"a             : {a}")

# nagat elements of a 
b=-a
print(f'b=-a          : {b}')

# sum all elements of a, returns a scalar
b=np.sum(a)
print(f"b = np.sum(a) : {b}")

b=np.mean(a)
print(f"b = np.mean(a): {b}")

b=a**2
print(f"b = a**2      : {b}")

a             : [1 2 3 4]
b=-a          : [-1 -2 -3 -4]
b = np.sum(a) : 10
b = np.mean(a): 2.5
b = a**2      : [ 1  4  9 16]


Most of the NumPy arithmetic, logical and comparison operations apply to vectors as well. These operators work on an element-by-element basis. For example 
$$ c_i = a_i + b_i $$

In [31]:
# vector vector element wise operations
a=np.array([1,2,3,4])
b=np.array([-1,-2,3,4])
print(f"Binary operators work element wise: {a + b}")

Binary operators work element wise: [0 0 6 8]


In [32]:
# try  a mismatched vector operations 

c=np.array([1,2])

try:
    d=a+c
except Exception as e:
    print('error message')
    print(e)

error message
operands could not be broadcast together with shapes (4,) (2,) 


In [33]:
# scalr vector operations 

a=np.array([1,2,3,4])

# multiplay a by a scalar
b=5*a
print(f"b = 5 * a : {b}")

b = 5 * a : [ 5 10 15 20]


**Using a for loop**, implement a function which returns the dot product of two vectors. The function to return given inputs $a$ and $b$:
$$ x = \sum_{i=0}^{n-1} a_i b_i $$
Assume both `a` and `b` are the same shape.

In [40]:
# dot product --> only works in 1D 
        

"""
Compute the dot product of two vectors

Args:
    a (ndarray (n,)):  input vector 
    b (ndarray (n,)):  input vector with same dimension as a

Returns:
    x (scalar): 
"""
def my_dot(a,b):
    x=0
    for i in range(a.shape[0]):
        x+= a[i]*b[i]
    return x

In [41]:
# test 1D
a = np.array([1, 2, 3, 4])
b = np.array([-1, 4, 3, 2])
print(f"my_dot(a, b) = {my_dot(a, b)}")

my_dot(a, b) = 24


In [42]:
#using np.dot function 
a = np.array([1, 2, 3, 4])
b = np.array([-1, 4, 3, 2])
c=np.dot(a,b)
print(f"NumPy 1-D np.dot(a, b) = {c}, np.dot(a, b).shape = {c.shape} ") 
c=np.dot(b,a)
print(f"NumPy 1-D np.dot(b, a) = {c}, np.dot(a, b).shape = {c.shape} ")

NumPy 1-D np.dot(a, b) = 24, np.dot(a, b).shape = () 
NumPy 1-D np.dot(b, a) = 24, np.dot(a, b).shape = () 
